name: Daily Commit Automation

on:
  schedule:
    # Runs once every day at 10:30 UTC (you can change this time)
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit by 24f2007798@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date)" > update_log.txt
          git config --local user.email "24f2007798@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Action Bot"
          git add update_log.txt
          git commit -m "Automated daily update on $(date)"
          git push
